language: ruby
rvm:
  - 2.2
  - jruby
  - 2.0.0-p247
deploy:
  provider: heroku
  api_key:
    secure: A0g7DRHURYp6V6xCL/UAx8vVRh392PXnIG1K1EPYcJULJys+KjNIeK7PqpvsqZy2EBsRocV/ypkMH9IiudJBPGU8zMRHXx1kvskAZw9LvBfuGG5wZGD2NQtXHYVMveEW64LrNGnvBRY8N4jxHzY6aiDEChjCr0/OVRrpHteYBOUW++Sxl3I9e1NX0C7zmDArYjwNjTy8jias/kJxaFEIWnN3blYR0zKYaR3tkzDqf1Y4BFE9S7+x3cAKQRIJ15qQQaGhlQ6Q6ZuDhRw9d0ph6k/thrJXlwwxMRf6FBn08Pbqg/J4rf8L3FSXuLjaSwuA/akZ+MFHs4jiBFL+kO9cxcF4JkJK2ZW/rfG8dt7+N9YhR8q1jbIeBqOCXQekZdtAK/S9/kJoPhaMCdEe0UiVfhRUeeP84Ea3UQ+lN6ulwGrEx9otA/lB7QDiWXK9gPJcs5OzUnRgjKUKdsCRX95ssBrbVPn++g9LIHrvnHaBCuXLw8d9ipLlD94Hw6zd7U60ZLlLCWffjWklLBszdDmsNf5MqPpAUzUh8hTU4FrrPdSKu9VaHqy2ni2A8nzNvX6mWScLBqX1nB+rA4Th/3UjjpQM/500ZyE6Ab0vMFsrGiQ8kNxWzrL3k4EK7+bseBN5ldMygajrMSKIlD7qHTyAQzsAg/nlQVzHwvPqTGLw3lg=
  app: trviad
