language: ruby
rvm:
  - 2.2
deploy:
  provider: heroku
  api_key:
    secure: a0Nm7wHy1AB8cmwwrSrFcqL5pOr+riNAjSa0uddhw4rDFwffykSSglrAqdA289EkZ7HIAL8RqXT5+OAJTdY6FobKW8QJzbufZ9h9iYyxVK7JfyjgsKmwewW3eWTVXwTBJL5LFExg54RNBivS6DbgPvDZyTUupz6//hoqcswSXNQxC2nifFroESv4ric0aXTxT00pJvpwG/j6rVJjYpGjzXDjE1ippaM58DnIcYOMXw8Mb741K2wCXAXXx7aT/V+IQTWXx0NzmJKSIekMl0tz7891kvHqhNtS3OYsxkDcuS6ol78Ef4FR9N8TH/bzI7Tyq8fpBibbtYEHFaTfNYL64SlUgPpcny23gmc7zpmPzEVVVlIjIISneSoGIn/KszI+fD2MBtA7nTz9JSW8KyzLcte4s0DLkyaUqhpHCPqN5/ApHwbHrAoBVvTQIgjsZuJnWGza9Io61yy9KXXYDx3w+VtMCFE0670+5U6J7784bqhH83vO8OU7Rbt7lZrZM1RDe4dIC299Pheb3wyPVlGcISv4NmLe+rRNah8uZz8AXcY/NhihT8fzhpdUVkjshztqcPnTi3ZH8FpMhisvYCng7LMU2RKftVYo2/yEt48KJMQwRTFPXR+ThHhIKQSEYu2Y+eRXu1998iPWGiVwz380S/AxsNiOeMQrU5CvHFJlxow=
  app: trviad
